always use D2L npm proxy registry

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -29,10 +29,11 @@ inputs:
     description: 'The token used as Authorization header when fetching from the mirror'
   d2l-registry-token:
     description: 'The auth token for package-registry.brightspace.com. Should be set to secrets.D2L_PACKAGE_REGISTRY_AUTH_TOKEN.'
+    required: true
 # TODO: add input to control forcing to pull from cloud or dist.
 #       escape valve for someone having issues or needing the absolute latest which isn't cached yet
 outputs:
-  cache-hit: 
+  cache-hit:
     description: 'A boolean value to indicate if a cache was hit.'
     value: ${{ steps.setup_node.outputs.cache-hit }}
   node-version:
@@ -42,6 +43,16 @@ outputs:
 runs:
   using: composite
   steps:
+    - name: Validate d2l-registry-token input
+      shell: bash
+      env:
+        NODE_AUTH_TOKEN: ${{ inputs.d2l-registry-token }}
+      run: |
+        if [[ -z "$NODE_AUTH_TOKEN" ]]; then
+          echo "::error::The d2l-registry-token input is required and must be set to secrets.D2L_PACKAGE_REGISTRY_AUTH_TOKEN."
+          exit 1
+        fi
+
     - id: setup_node
       uses: Brightspace/third-party-actions@actions/setup-node
       with:
@@ -49,7 +60,7 @@ runs:
         node-version-file: ${{ inputs.node-version-file }}
         architecture: ${{ inputs.architecture }}
         check-latest: ${{ inputs.check-latest }}
-        registry-url: ${{ case(inputs.d2l-registry-token != '', 'https://npm.package-registry.brightspace.com', '') }}
+        registry-url: https://npm.package-registry.brightspace.com
         scope: ${{ inputs.scope }}
         token: ${{ inputs.token }}
         cache: ${{ inputs.cache }}
@@ -59,29 +70,3 @@ runs:
         mirror-token: ${{ inputs.mirror-token }}
       env:
         NODE_AUTH_TOKEN: ${{ inputs.d2l-registry-token }}
-
-    - if: '! inputs.d2l-registry-token'
-      uses: Brightspace/third-party-actions@actions/checkout
-      with:
-        repository: Brightspace/safe-chain-tmp
-        path: ./.safe-chain-tmp
-        sparse-checkout: |
-          d2l-safe-chain.tgz
-
-    - name: Install @d2l/safe-chain
-      if: '! inputs.d2l-registry-token'
-      shell: bash
-      run: |
-        npm i --global --ignore-scripts ./.safe-chain-tmp/d2l-safe-chain.tgz
-
-    - name: Cleanup checkout
-      if: '! inputs.d2l-registry-token'
-      shell: bash
-      run: |
-        rm -rf ./.safe-chain-tmp
-
-    - name: Set Up safe-chain
-      if: '! inputs.d2l-registry-token'
-      shell: bash
-      run: |
-        safe-chain setup-ci
